apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-example
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-example
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets", "configmaps" ]
    verbs: [ "get", "watch", "list", "update", "create" ]
  - apiGroups: [ "apiregistration.k8s.io" ]
    resources: [ "apiservices"]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "admissionregistration.k8s.io" ]
    resources: [ "validatingwebhookconfigurations", "mutatingwebhookconfigurations" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-example
subjects:
  - kind: ServiceAccount
    name: webhook-example
    namespace: default
